/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEmbeddingResponseDataInner {
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "object")]
    pub object: String,
    #[serde(rename = "embedding")]
    pub embedding: Vec<f32>,
}

impl CreateEmbeddingResponseDataInner {
    pub fn new(index: i32, object: String, embedding: Vec<f32>) -> CreateEmbeddingResponseDataInner {
        CreateEmbeddingResponseDataInner {
            index,
            object,
            embedding,
        }
    }
}


