/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEmbeddingResponse {
    #[serde(rename = "object")]
    pub object: String,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "data")]
    pub data: Vec<crate::models::CreateEmbeddingResponseDataInner>,
    #[serde(rename = "usage")]
    pub usage: Box<crate::models::CreateEmbeddingResponseUsage>,
}

impl CreateEmbeddingResponse {
    pub fn new(object: String, model: String, data: Vec<crate::models::CreateEmbeddingResponseDataInner>, usage: crate::models::CreateEmbeddingResponseUsage) -> CreateEmbeddingResponse {
        CreateEmbeddingResponse {
            object,
            model,
            data,
            usage: Box::new(usage),
        }
    }
}


