/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateSearchResponseDataInner {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "document", skip_serializing_if = "Option::is_none")]
    pub document: Option<i32>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
}

impl CreateSearchResponseDataInner {
    pub fn new() -> CreateSearchResponseDataInner {
        CreateSearchResponseDataInner {
            object: None,
            document: None,
            score: None,
        }
    }
}


