/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateAnswerRequestStop : Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAnswerRequestStop {
}

impl CreateAnswerRequestStop {
    /// Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence. 
    pub fn new() -> CreateAnswerRequestStop {
        CreateAnswerRequestStop {
        }
    }
}


