/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTranscriptionResponse {
    #[serde(rename = "text")]
    pub text: String,
}

impl CreateTranscriptionResponse {
    pub fn new(text: String) -> CreateTranscriptionResponse {
        CreateTranscriptionResponse {
            text,
        }
    }
}


