/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEmbeddingRequest {
    /// ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them.
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "input")]
    pub input: Box<crate::models::CreateEmbeddingRequestInput>,
    /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids). 
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

impl CreateEmbeddingRequest {
    pub fn new(model: String, input: crate::models::CreateEmbeddingRequestInput) -> CreateEmbeddingRequest {
        CreateEmbeddingRequest {
            model,
            input: Box::new(input),
            user: None,
        }
    }
}


