/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateModerationRequestInput : The input text to classify



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateModerationRequestInput {
}

impl CreateModerationRequestInput {
    /// The input text to classify
    pub fn new() -> CreateModerationRequestInput {
        CreateModerationRequestInput {
        }
    }
}


