/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FineTuneEvent {
    #[serde(rename = "object")]
    pub object: String,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(rename = "level")]
    pub level: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl FineTuneEvent {
    pub fn new(object: String, created_at: i32, level: String, message: String) -> FineTuneEvent {
        FineTuneEvent {
            object,
            created_at,
            level,
            message,
        }
    }
}


